Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-03a6eaae9938c858c

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap 
        - RegionMap
        - !Ref AWS::Region
        - AMI
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: !Join [ " ", [ EC2, Instance, for, !Ref AWS::Region ] ]
      SecurityGroupIds: 
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access 
      VpcId: # required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0